"""
KronOS Backend — Flask + SocketIO real-time OS monitor.

Architecture:
  - WebSocket (flask-socketio) emits 'metrics_update' every 2s  [TASK 2]
  - REST endpoints kept as fallback                              [TASK 2]
  - In-memory TTL cache for psutil reads + ML predictions        [TASK 3]
  - /api/processes returns JSON, top-N, searchable               [TASK 4]
"""

from flask import Flask, jsonify, request, render_template
from flask_cors import CORS
from flask_socketio import SocketIO, emit
import psutil
import joblib
import os
import shutil
import time
import threading
from typing import Dict, List, Optional, Any


# ==========================================================================
# Flask + SocketIO initialisation
# ==========================================================================

# Initialise Flask with paths to the Frontend directory for templates/static
app = Flask(
    __name__,
    static_folder="../Frontend/static",
    template_folder="../Frontend/templates",
)
CORS(app)

# SocketIO — using threading async_mode (works on Windows without eventlet)
socketio = SocketIO(app, cors_allowed_origins="*", async_mode="threading")


# ==========================================================================
# Load pre-trained ML artefacts (generated by model.py)
# ==========================================================================

current_dir: str = os.path.dirname(os.path.abspath(__file__))
models_dir: str = os.path.join(current_dir, "models")

try:
    model_path = os.path.join(models_dir, "anomaly_detection_model.pkl")
    scaler_path = os.path.join(models_dir, "scaler.pkl")
    model = joblib.load(model_path)
    scaler = joblib.load(scaler_path)
    print("Model and scaler loaded successfully.")
except Exception as e:
    print(f"Error loading model or scaler: {e}")
    print(f"Looking for models in: {models_dir}")
    exit()


# ==========================================================================
# TASK 3 — In-memory TTL cache
# ==========================================================================

class TTLCache:
    """Simple dict-based cache with per-key TTL (in seconds)."""

    def __init__(self) -> None:
        self._store: Dict[str, Any] = {}
        self._timestamps: Dict[str, float] = {}

    def get(self, key: str, ttl: float) -> Optional[Any]:
        """Return cached value if within TTL, else None."""
        ts = self._timestamps.get(key)
        if ts is not None and (time.time() - ts) < ttl:
            return self._store[key]
        return None

    def set(self, key: str, value: Any) -> None:
        """Store a value and record current timestamp."""
        self._store[key] = value
        self._timestamps[key] = time.time()


cache = TTLCache()

# TTL constants (seconds)
PSUTIL_TTL: float = 1.5   # Cache raw psutil metrics for 1.5 s
ML_TTL: float = 2.0       # Cache ML prediction for 2 s


# ==========================================================================
# System metrics helpers
# ==========================================================================

def get_system_metrics_cached() -> Dict[str, Any]:
    """
    Read CPU / memory / disk / process_count via psutil.
    Returns cached result if within PSUTIL_TTL.
    """
    cached = cache.get("psutil_metrics", PSUTIL_TTL)
    if cached is not None:
        return cached

    cpu = psutil.cpu_percent(interval=0.5)
    memory = psutil.virtual_memory().percent

    # shutil.disk_usage works on Windows (psutil.disk_usage is broken in 5.9.0)
    disk_path = "C:" if os.name == "nt" else "/"
    d_total, d_used, _ = shutil.disk_usage(disk_path)
    disk = round(d_used / d_total * 100, 1)

    process_count = len(list(psutil.process_iter()))

    metrics = {
        "cpu_usage": cpu,
        "memory_usage": memory,
        "disk_usage": disk,
        "process_count": process_count,
    }
    cache.set("psutil_metrics", metrics)
    return metrics


def get_prediction_cached(metrics: Dict[str, Any]) -> Dict[str, Any]:
    """
    Run ML inference on the 4-feature vector.
    Returns cached result if within ML_TTL.
    Includes 'status' (Normal|Anomaly) and 'confidence' (0–1).
    """
    cached = cache.get("ml_prediction", ML_TTL)
    if cached is not None:
        return cached

    import numpy as np
    features = np.array([[
        metrics["cpu_usage"],
        metrics["memory_usage"],
        metrics["disk_usage"],
        metrics["process_count"],
    ]])
    scaled = scaler.transform(features)
    prediction = model.predict(scaled)[0]
    probabilities = model.predict_proba(scaled)[0]
    confidence = float(max(probabilities))

    result = {
        "status": "Normal" if prediction == 1 else "Anomaly",
        "confidence": round(confidence, 4),
    }
    cache.set("ml_prediction", result)
    return result


def build_suggestions(status: str, cpu: float, memory: float, disk: float) -> List[str]:
    """Generate actionable suggestions based on anomaly status and metric values."""
    if status != "Anomaly":
        return ["System is operating normally."]
    suggestions: List[str] = []
    if cpu > 85:
        suggestions.append("High CPU usage detected. Close unnecessary applications.")
    if memory > 85:
        suggestions.append("High memory usage detected. Free up memory by closing unused apps.")
    if disk > 90:
        suggestions.append("Disk usage critically high. Free up disk space.")
    suggestions.append("Check for zombie or orphan processes and terminate them.")
    suggestions.append("Monitor CPU temperature to prevent overheating.")
    return suggestions


def build_full_payload() -> Dict[str, Any]:
    """Assemble the complete metrics + ML + suggestions payload."""
    metrics = get_system_metrics_cached()
    prediction = get_prediction_cached(metrics)
    suggestions = build_suggestions(
        prediction["status"],
        metrics["cpu_usage"],
        metrics["memory_usage"],
        metrics["disk_usage"],
    )
    return {
        **metrics,
        **prediction,
        "suggestions": suggestions,
    }


# ==========================================================================
# TASK 2 — WebSocket: emit metrics_update every 2 seconds
# ==========================================================================

def background_emitter() -> None:
    """
    Runs in a daemon thread. Every 2 seconds it reads system metrics,
    runs ML inference (with caching), and emits 'metrics_update' to
    all connected WebSocket clients.
    """
    while True:
        try:
            payload = build_full_payload()
            socketio.emit("metrics_update", payload)
        except Exception as e:
            print(f"[emitter] Error: {e}")
        socketio.sleep(2)


@socketio.on("connect")
def handle_connect() -> None:
    """Send an immediate update when a client connects."""
    try:
        payload = build_full_payload()
        emit("metrics_update", payload)
    except Exception as e:
        print(f"[connect] Error: {e}")


# ==========================================================================
# REST endpoints (kept as fallback)
# ==========================================================================

@app.route("/")
def index() -> str:
    """Serve the main dashboard HTML template."""
    return render_template("index.html")


@app.route("/api/system-metrics", methods=["GET"])
def api_system_metrics():
    """REST fallback — returns CPU, memory, disk, process_count + anomaly status."""
    try:
        payload = build_full_payload()
        return jsonify(payload)
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/api/anomalies", methods=["GET"])
def api_anomalies():
    """REST fallback — returns anomaly status + suggestions."""
    try:
        payload = build_full_payload()
        return jsonify({
            "status": payload["status"],
            "confidence": payload["confidence"],
            "suggestions": payload["suggestions"],
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500


# ==========================================================================
# TASK 4 — /api/processes  (JSON, top-N, searchable)
# ==========================================================================

@app.route("/api/processes", methods=["GET"])
def api_processes():
    """
    Return JSON list of running processes sorted by cpu_percent desc.
    Query params:
      ?search=<name>   — filter by process name (case-insensitive)
      ?limit=<int>     — max results (default 50, max 200)
    """
    try:
        search: str = request.args.get("search", "").lower()
        limit: int = min(int(request.args.get("limit", 50)), 200)

        processes: List[Dict[str, Any]] = []
        for proc in psutil.process_iter(["pid", "name", "cpu_percent", "memory_percent", "status", "username"]):
            try:
                info = proc.info
                # Apply search filter
                if search and search not in (info.get("name") or "").lower():
                    continue
                processes.append({
                    "pid": info.get("pid"),
                    "name": info.get("name", "Unknown"),
                    "cpu_percent": info.get("cpu_percent", 0.0) or 0.0,
                    "memory_percent": round(info.get("memory_percent", 0.0) or 0.0, 2),
                    "status": info.get("status", "unknown"),
                    "username": info.get("username", "N/A"),
                })
            except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
                continue

        # Sort by CPU desc, slice to limit
        processes.sort(key=lambda p: p["cpu_percent"], reverse=True)
        return jsonify(processes[:limit])
    except Exception as e:
        return jsonify({"error": str(e)}), 500


# Legacy /processes route — redirect to the dashboard (processes are now client-rendered)
@app.route("/processes")
def processes_page() -> str:
    """Serve the main dashboard — the processes tab is now rendered client-side."""
    return render_template("index.html")


# ==========================================================================
# Entry point
# ==========================================================================

if __name__ == "__main__":
    # Start the background emitter thread
    emitter_thread = threading.Thread(target=background_emitter, daemon=True)
    emitter_thread.start()

    # Run with SocketIO (handles both HTTP and WebSocket)
    socketio.run(app, debug=True, host="0.0.0.0", port=5000, use_reloader=False, allow_unsafe_werkzeug=True)